version: '3.9'

services:
  telegram-bot:
    build: ./
    container_name: felix-telegram-bot
    hostname: telegram-bot
    restart: always
    entrypoint: /usr/src/app/entrypoint.sh
    command: python main.py
    expose:
      - 8080
    env_file:
      - .env.dev
    volumes:
      - ./felix/:/usr/src/app/
    networks:
      backend-network:
        ipv4_address: 10.5.0.5
  db:
    image: mysql:8.0
    restart: always
    container_name: felix-db
    hostname: db
    expose:
      - 3306:3306
    env_file:
      - .env.dev
    volumes:
      - dev-db:/var/lib/mysql
    networks:
      backend-network:
        ipv4_address: 10.5.0.4

volumes:
  dev-db:


networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
